name: Deploy Laravel to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}
            sudo git pull origin main
            sudo composer install --no-dev --optimize-autoloader
            sudo php artisan config:clear
            sudo php artisan cache:clear
            sudo php artisan route:clear
            sudo systemctl restart apache2  # Change to nginx if using Nginx
          EOF